name: Habij Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Lint and Format
        run: |
          poetry run ruff check .
          poetry run ruff check . --fix

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint # Ensures this job runs after linting
    # if: github.ref == 'refs/heads/main' # Only runs on push to main branch
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          REPO_NAME="habij-backend"
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/$REPO_NAME
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  generate-types:
    name: Generate TypeScript Types
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/main' # Only runs on push to main branch
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Generate OpenAPI Schema
        run: poetry run python manage.py spectacular --file schema.json

      - name: Generate TypeScript Types
        run: |
          npx @openapitools/openapi-generator-cli generate \
            -i schema.json \
            -g typescript-fetch \
            -o generated-types

      - name: Push Generated Types to habij-types
        env:
          PAT_HABIJ_TYPES: ${{ secrets.secrets.REPO_ACCESS_TOKEN }}
        run: |
          git clone https://x-access-token:${PAT_HABIJ_TYPES}@github.com/gethabij/habij-types.git types-repo

          # Debug: Check generated types
          ls -la generated-types
          cat generated-types/schema.ts || echo "No schema.ts found"

          # Clean and copy
          cd types-repo
          git rm -r * || true
          cp -r ../generated-types/* .
          git add .

          # Commit and push changes
          git diff --quiet && echo "No changes to commit" || git commit -m "chore: update generated types at $(date)"
          git push origin main

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build # Ensures this job runs after the build job
    if: github.ref == 'refs/heads/main' # Only runs on push to main branch
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          # Create the SSH directory
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write the private key to the file
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add the VPS to known hosts
          ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts

          # SSH into the VPS and deploy
          ssh $VPS_USER@$VPS_IP << 'EOF'

          REPO_NAME="habij-backend"
          CONTAINER_NAME="${REPO_NAME}"
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/$REPO_NAME

          # Pull the latest Docker image
          docker pull $IMAGE_NAME:latest


          # Stop and remove any existing container with the same name
          if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
              docker stop $CONTAINER_NAME
              docker rm $CONTAINER_NAME
          fi

          # Ensure the environment file exists
          if [ ! -f /etc/$REPO_NAME/env/$REPO_NAME.env ]; then
              echo "Environment file missing at /etc/$REPO_NAME/env/$REPO_NAME.env"
              exit 1
          fi

          docker run -d --name $CONTAINER_NAME -p 8000:8000 \
            --env-file /etc/$REPO_NAME/env/$REPO_NAME.env \
            $IMAGE_NAME:latest

          # Reload Nginx
          sudo systemctl reload nginx
          EOF
